finances/urls.py
from django.urls import path
from .views import MovementCreateView, MovementUpdateView, MovementDeleteView, MovementAdminListView, MakePaymentFunc, PaymentRedirectView

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('validate/<int:usr>/<int:year>/<int:month>/', MovementAdminListView.as_view(), name = 'finances_validate'),
    path('pagar_fact/', MakePaymentFunc.as_view(), name = 'finances_pay'),
    path('lastmov/', PaymentRedirectView.as_view(), name='finances_last'),
]

inamex/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    # django admin app
    path('app/_dft_wedb4p__eds/', admin.site.urls),
    # user management app
    path('app/accounts/', include('allauth.urls')),
    path('app/login/', LoginView.as_view()),
    path('app/signup/', SignupView.as_view()),
    # local apps
    path('app/', include('pages.urls')),
    path('app/finances/', include('finances.urls'),)
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Inamex{% endblock title %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>


  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    
    <div class="container-fluid">
      <a class="navbar-brand" href="">INAMEX: {{ user|title }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
          {% if perms.finances.do_payments %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'finances:finances_last' %}">Pagos</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'finances:finances_home' %}">Viaticos</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="" method="get">
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" >
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  
  <div class="container pt-5 mt-3">
    {% block content %}
    {% endblock content %}
  </div>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

{% block scripts %}
{% endblock %}
</body>
</html>

templates/home.html
{% extends "_base.html" %}
{% load static %}

{% block title %}InamexApp{% endblock title %}

{% block content %}
<h2>Inamex-APP</h2>
<h3>HOME</h3>

{% endblock content %}