finances/urls.py
from django.urls import path
from .views import MovementCreateView, MovementUpdateView, MovementDeleteView, MovementAdminListView, MakePaymentFunc, PaymentRedirectView

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('validate/<int:usr>/<int:year>/<int:month>/', MovementAdminListView.as_view(), name = 'finances_validate'),
    path('pagar_fact/', MakePaymentFunc.as_view(), name = 'finances_pay'),
    path('lastmov/', PaymentRedirectView.as_view(), name='finances_last'),
]

inamex/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    # django admin app
    path('app/_dft_wedb4p__eds/', admin.site.urls),
    # user management app
    path('app/accounts/', include('allauth.urls')),
    path('app/login/', LoginView.as_view()),
    path('app/signup/', SignupView.as_view()),
    # local apps
    path('app/', include('pages.urls')),
    path('app/finances/', include('finances.urls'),)
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

finances/models.py
from django.db import models
from accounts.models import CustomUser
#from projects.models import Project
#from business.models import Supplier
from datetime import datetime

class Movement(models.Model):
    payee = models.CharField(
        max_length=254
    )
    creation_date = models.DateField(
        default = datetime.now,
    )
    description = models.CharField(
        max_length=254
    )
    amount = models.DecimalField(
        decimal_places=3,
        max_digits=7
    )
    no_invoice = models.BooleanField(
        blank = True,
        default = False
    )
    payment = models.BooleanField(
        blank = True,
        default = False
    )
    responsable = models.ForeignKey(
        CustomUser,
        models.CASCADE,
        related_name='%(class)s_responsable',
    )
    files = models.FileField(
        blank = True,
        null = True
    )
    
    class Meta:
        permissions = [
            ("do_payments", "Can do payments"),
        ]
    
    def __str__(self):
        return self.payee

finances/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth.models import User
from datetime import datetime
from finances.models import Movement

class MovementCreateForm(forms.ModelForm):
    class Meta:
        model = Movement
        fields = '__all__'
        widgets = {
            'payee':forms.TextInput(attrs={'class':'form-control'}),
            'creation_date':forms.DateInput(attrs={'class':'form-control datepicker','type':'date'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
            'amount':forms.NumberInput(attrs={'class':'form-control'}),
            'no_invoice':forms.NullBooleanSelect(attrs={'class':'form-control'}),
            'payment':forms.NullBooleanSelect(attrs={'class':'form-control'}),
            'responsable':forms.Select(attrs={'class':'form-control'}),
            'files':forms.FileInput(attrs={'class':'form-control'}),
        }

'''class ProjectSelect(ModelChoiceField):
    def label_from_instance(self, obj):
        return "{}".format(
            obj.name
        )

class UserSelect(ModelChoiceField):
    def label_from_instance(self,obj):
        return '{}'.format(
            obj.username
        )

class PayeeSelect(ModelChoiceField):
    def label_from_instance(self, obj):
        return '{}'.format(
            obj.name
        )

class NewMovement(forms.Form):
    payee = PayeeSelect(
        label = 'Proveedor',
        queryset=Supplier.objects.all(),
        required = False,
    )

    creation_date = forms.DateField(
        label = "Fecha", 
        widget = forms.DateInput(
            format=('%m/%d/%Y'),
            attrs={
                'class':'datepicker',
                'type':'date',
            },
        )
    )
    project = ProjectSelect(
        label = "Proyecto",
        queryset = Project.objects.all(),
        required = False
    )
    description = forms.CharField(
        label = "Descripcion",
        max_length = 254,
        widget = forms.Textarea(
            attrs={
                'cols':'30',
                'rows':'2'
            }
        )
    )
    amount = forms.DecimalField(
        label = "Monto",
        decimal_places=3,
        max_digits=7
    )
    no_invoice = forms.BooleanField(
        label = "Sin factura",
        required = False,
        initial = False
    )
    payment = forms.BooleanField(
        label = "Pagado",
        required = False,
        initial = False
    )
    account = UserSelect(
        label = "Responsable",
        queryset = User.objects.all(),
    )
    files = forms.FileField(
        label = "Archivos",
        max_length=60,
        required = False
    )'''

finances/views.py
from django.db.models import Sum

from django.views.generic import (
    CreateView, UpdateView, DeleteView, ListView,
    RedirectView, MonthArchiveView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Movement
from .forms import MovementCreateForm
from accounts.models import CustomUser

import datetime

class MovementCreateView(LoginRequiredMixin,CreateView):
    model = Movement
    #fields = '__all__'
    form_class = MovementCreateForm
    success_url = reverse_lazy("finances:finances_home")

    def get_form_kwargs(self):
        kwargs = super(MovementCreateView, self).get_form_kwargs()
        u = self.request.user
        kwargs['initial']= {
            'responsable':u.pk,
        }
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context =  super(MovementCreateView, self).get_context_data(*args, **kwargs)
        context['no_invoice'] = Movement.objects.filter(
            no_invoice = True,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        )
        context['invoice'] = Movement.objects.filter(
            no_invoice = False,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        )
        context['total_fact'] = context['invoice'].filter(
            no_invoice=False
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        context['total_no_fact'] = context['no_invoice'].filter(
            no_invoice = True
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        return context

class MovementUpdateView(LoginRequiredMixin, UpdateView):
    model = Movement
    #fields = '__all__'
    form_class = MovementCreateForm
    success_url = reverse_lazy("finances:finances_home")

    def get_context_data(self, *args, **kwargs):
        context =  super(MovementUpdateView, self).get_context_data(*args, **kwargs)
        context['no_invoice'] = Movement.objects.filter(
            no_invoice = True,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        )
        context['invoice'] = Movement.objects.filter(
            no_invoice = False,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        )
        context['total_fact'] = context['invoice'].filter(
            no_invoice=False
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        context['total_no_fact'] = context['no_invoice'].filter(
            no_invoice = True
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        return context

class MovementDeleteView(LoginRequiredMixin, DeleteView):
    model = Movement
    success_url = reverse_lazy("finances:finances_home")

class MovementAdminListView(LoginRequiredMixin, ListView):
    model = Movement
    # context_object_name = 'movement_list'
    
    def get_context_data(self, **kwargs):
        usuario = self.kwargs['usr']
        context =  super(MovementAdminListView, self).get_context_data(**kwargs)
        
        context["next_user"] = CustomUser.objects.filter(id__gt=usuario).order_by('id').first()
        context["prev_user"] = CustomUser.objects.filter(id__lt=usuario).order_by('-id').first()
        
        context["usuario"] = CustomUser.objects.get(pk=usuario)
        
        context["month_movements"] = context["usuario"].movement_responsable.all().filter(
            creation_date__year=self.kwargs['year'],
            creation_date__month=self.kwargs['month'],
        )
        
        context["next_month_movements"] = context["usuario"].movement_responsable.all().filter(
            creation_date__year=self.kwargs['year'],
            creation_date__month__gt=self.kwargs['month'],
        ).order_by('id').first()
        context["prev_month_movements"] = context["usuario"].movement_responsable.all().filter(
            creation_date__year=self.kwargs['year'],
            creation_date__month__lt=self.kwargs['month'],
        ).order_by('-id').first()
        
        if context["month_movements"].first():
            context['first_date'] = context["month_movements"].first().creation_date
        else:
            context['first_date'] = datetime.datetime.now()
        
        context['total_fact'] = context["month_movements"].filter(
            no_invoice=False,
            payment = False,
        ).aggregate(
            Sum('amount') 
        )['amount__sum']
        
        context['total_no_fact'] = context["month_movements"].filter(
            no_invoice = True,
            payment = False,
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        
        fact_ids = context["month_movements"].filter(
            no_invoice=False,
            payment = False,
        )
        
        no_fact_ids = context["month_movements"].filter(
            no_invoice=True,
            payment = False,
        )
        # Create Fact_ids str
        context['fact_ids'] = ""
        for fact_id in fact_ids:
            context['fact_ids'] += str(fact_id.pk)
            context['fact_ids'] += ","
        context['fact_ids'] = context['fact_ids'][:-1]
        # Create no_Fact_ids str
        context['no_fact_ids'] = ""
        for no_fact_id in no_fact_ids:
            context['no_fact_ids'] += str(no_fact_id.pk)
            context['no_fact_ids'] += ","
        context['no_fact_ids'] = context['no_fact_ids'][:-1]
        return context

class PaymentRedirectView(RedirectView):
    try:
        movimiento = Movement.objects.all().order_by('-id').first()
    except:
        movimiento = None
    print(movimiento)
    if not movimiento:
        url = reverse_lazy("finances:finances_validate", kwargs={
            'usr':'1',
            'year':'2022',
            'month':'1',
        })
    else:
        url = reverse_lazy("finances:finances_validate", kwargs={
            'usr':movimiento.responsable.pk,
            'year':movimiento.creation_date.year,
            'month':movimiento.creation_date.month,
        })
    
class MakePaymentFunc(LoginRequiredMixin, RedirectView):
    url = reverse_lazy("finances:finances_home")
    
    def get_redirect_url(self, *args, **kwargs):
        por_pagar = [int(x) for x in self.request.GET.get('paymentlist').split(",")]
        for mov_id in por_pagar:
            m = Movement.objects.get(pk=mov_id)
            m.payment = True
            m.save()
        return super().get_redirect_url(*args, **kwargs)

templates/finances/movement_archive_month.html
<h1>{{ month }}</h1>

<ul>
    {% for article in object_list %}
        <li>{{ article.creation_date|date:"F j, Y" }}: {{ article.payee }}</li>
    {% endfor %}
</ul>

<p>
    {% if previous_month %}
        Previous Day: {{ previous_month }}
    {% endif %}
    {% if previous_month and next_month %}--{% endif %}
    {% if next_month %}
        Next Day: {{ next_month }}
    {% endif %}
</p>


{% extends '_base.html' %}
{% block title %}
    Movement | Form
{% endblock title %}

{% block content %}

<div class="col col-lg-9">
    <h3>Balance del mes actual de {{usuario|title}} </h3>

    {% regroup usuario.movement_responsable.all|dictsort:"no_invoice" by no_invoice as invoice_list %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Fecha</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Monto</th>
                <th scope="col">Pagado</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for invoice in invoice_list %}
            {% if invoice.grouper == False %}
                <tr>
                    <th scope="col" colspan="3">Movimientos facturables</th>
                    <th scope="col" colspan="2">${{total_fact|stringformat:"2.2f"}}</th>
                    {% if fact_ids %}
                    <td scope="col"><a class="btn btn-outline-success btn-sm" href="{% url 'finances:finances_pay' %}?paymentlist={{fact_ids}}" role="button">Pagar </a></td>
                    {% endif %}
                </tr>
            {% else %}
                <tr>
                    <th scope="col" colspan="3">Movimientos NO facturables</th>
                    <th scope="col" colspan="2">${{total_no_fact|stringformat:"2.2f"}}</th>
                    <td scope="col"><a class="btn btn-outline-success btn-sm" href="{% url 'finances:finances_pay' %}?paymentlist={{no_fact_ids}}" role="button">Pagar </a></td>
                </tr>
            {% endif %}
            {% for reg in invoice.list %}
                <tr>
                    <td scope="col">{{ reg.id }}.- {{ reg.payee }}</td>
                    <td scope="col">{{ reg.creation_date }}</td>
                    <td scope="col">{{ reg.description }}</td>
                    <td scope="col">{{ reg.amount|stringformat:"2.2f" }}</td>
                    {% if reg.payment %}
                    <td scope="col"><span class="badge rounded-pill bg-success">SI</span></td>
                    {% else %}
                    <td scope="col"><span class="badge rounded-pill bg-warning text-dark">NO</span></td>
                    {% endif %}
                    <td scope="col"><a class="btn btn-outline-danger btn-sm" href="{% url 'finances:finances_delete' reg.pk %}" role="button">Borrar</a></td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>
</div>

{% endblock content %}

{% block scripts %}
{% endblock scripts %}

templates/finances/movement_confirm_delete.html
{% extends '_base.html' %}

{% block title %}
    Finances | Delete
{% endblock title %}

{% block content %}
<h1>Are you sure you want to delete this movement?</h1>
<ul>
    <li>ID: {{movement.id}}</li>
    <li>PAYEE: {{movement.payee}}</li>
    <li>AMOUNT: $ {{movement.amount|stringformat:"2.2f"}}</li>
    <li>DESCRIPTION: {{movement.description}}</li>
</ul>
<form method='POST'>
    {% csrf_token %}
    <input type="submit" value="Confirm Delte">
</form>

{% endblock content %}

{% block scripts %}
{% endblock %}

templates/finances/movement_form.html
{% extends '_base.html' %}

{% block title %}
    Movement | Form
{% endblock title %}

{% block content %}

<div class="col col-lg-9">
    <form method="post">
        {% csrf_token %}
        {{form.as_table}}
        <input class="btn btn-primary mb-3" type="submit" value="Submit">
    </form>
</div>

<div class="col col-lg-9">
    <h3>Balance del mes actual</h3>
    <p>
        Total facturable: ${{total_fact|stringformat:"2.2f"}}
    </p>
    <p>
        Total no facturable: ${{total_no_fact|stringformat:"2.2f"}}
    </p>

    <h3>Movimientos facturables</h3>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Fecha</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Monto</th>
                <th scope="col">Pagado</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in invoice %}
        <tr>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date }}</td>
            <td scope="col">{{ reg.description }}</td>
            <td scope="col">{{ reg.amount|stringformat:"2.2f" }}</td>
            <td scope="col">{{ reg.payment }}</td>
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">Borrar</a></th>
        </tr>
        {% endfor %}
    </table>

    <h3>Movimientos NO facturables</h3>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Fecha</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Monto</th>
                <th scope="col">Pagado</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in no_invoice %}
        <tr>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date }}</td>
            <td scope="col">{{ reg.description }}</td>
            <td scope="col">${{ reg.amount|stringformat:"6.2f" }}</td>
            <td scope="col">{{ reg.payment }}</td>
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">Borrar</a></th>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

{% block scripts %}
{% endblock %}

templates/finances/movement_list.html
{% extends '_base.html' %}
{% block title %}
    Movement | Form
{% endblock title %}

{% block content %}

<div class="col col-lg-9">
    <h3>Balance del mes {{ first_date|date:"F" }} de {{usuario|title}} </h3>

    {% regroup month_movements.all|dictsort:"no_invoice" by no_invoice as invoice_list %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Fecha</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Monto</th>
                <th scope="col">Pagado</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for invoice in invoice_list %}
            {% if invoice.grouper == False %}
                <tr>
                    <th scope="col" colspan="3">Movimientos facturables</th>
                    <th scope="col" colspan="2">${{total_fact|stringformat:"2.2f"}}</th>
                    {% if fact_ids %}
                    <td scope="col"><a class="btn btn-outline-success btn-sm" href="{% url 'finances:finances_pay' %}?paymentlist={{fact_ids}}" role="button">Pagar </a></td>
                    {% endif %}
                </tr>
            {% else %}
                <tr>
                    <th scope="col" colspan="3">Movimientos NO facturables</th>
                    <th scope="col" colspan="2">${{total_no_fact|stringformat:"2.2f"}}</th>
                    {% if no_fact_ids %}
                    <td scope="col"><a class="btn btn-outline-success btn-sm" href="{% url 'finances:finances_pay' %}?paymentlist={{no_fact_ids}}" role="button">Pagar </a></td>
                    {% endif %}
                </tr>
            {% endif %}
            {% for reg in invoice.list %}
                <tr>
                    <td scope="col">{{ reg.id }}.- {{ reg.payee }}</td>
                    <td scope="col">{{ reg.creation_date }}</td>
                    <td scope="col">{{ reg.description }}</td>
                    <td scope="col">{{ reg.amount|stringformat:"2.2f" }}</td>
                    {% if reg.payment %}
                    <td scope="col"><span class="badge rounded-pill bg-success">SI</span></td>
                    {% else %}
                    <td scope="col"><span class="badge rounded-pill bg-warning text-dark">NO</span></td>
                    {% endif %}
                    <td scope="col"><a class="btn btn-outline-danger btn-sm" href="{% url 'finances:finances_delete' reg.pk %}" role="button">Borrar</a></td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>
    {% if prev_month_movements %}
    <a class="btn btn-primary btn-sm" href="{% url 'finances:finances_validate' usuario.pk 2022 prev_month_movements.creation_date|date:"n" %}">Mes anterior</a>
    {% else %}
    Primer mes
    {% endif %}
    /
    {% if next_month_movements %}
    <a class="btn btn-primary btn-sm" href="{% url 'finances:finances_validate' usuario.pk 2022 next_month_movements.creation_date|date:"n" %}">Mes siguiente</a>
    {% else %}
    Ultimo mes
    {% endif %}
     -|-
    {% if prev_user %}
    <a class="btn btn-primary btn-sm" href="{% url 'finances:finances_validate' prev_user.pk 2022 first_date|date:"n" %}">Usuario anterior {{prev_user}}</a>
    {% else %}
    Primer usuario
    {% endif %}
     /
    {% if next_user %}
    <a class="btn btn-primary btn-sm" href="{% url 'finances:finances_validate' next_user.pk 2022 first_date|date:"n" %}">Usuario siguiente {{next_user}}</a>
    {% else %}
    Ultimo usuario
    {% endif %}
</div>

{% endblock content %}

{% block scripts %}
{% endblock scripts %}